### ISSUE TITLE
 wrong localstorage link 

### ISSUE THREAD

**Issue by sofiiadidovych** [HackYourFuture-CPH/JavaScript#125]
Hi! I noticed that localstorage link in _Save my location optional_ part leads to Geolocation API. 
I used this link instead https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage?fbclid=IwAR2XNXZKUe1OoND0jSUWTPHkykZyYhrBEzTTwmyYsfT2Jpk_5AK39m9hUoY

**Comment by benna100** [comment]
Ahh, prefect, can you update the link. You can do it all in the browser! Just click on the edit icon and then make a pr with the change
